# superuser level permissions
sudo: required
services:
  # to specify we need Docker
  - docker

before_install: 
  # we need to tag the image, so we can refer to it later
  - docker build -t isai2105/docker-react -f Dockerfile.dev .

script:
  # npm run test waits for input (just as in the terminal)
  # so we need a way to run it and having it exit when the test executions run
  - docker run -e CI=true isai2105/docker-react npm run test -- --coverage